### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by michaelthompson1991** [X1ZOR/homebridge-dummy-thermostat#6]
Hi, I’m just wondering what you would use this plugin for? I’ve downloaded it but I can’t see a use guy it 🤷🏼‍♂️

**Comment by nickstx** [comment]
Ditto, can’t figure out how to use this. I have a thermometer and a smart plug, really hoping I can use this to combine the two into a thermostat in HomeKit.

This plugin also seems to override the readout of the actual thermostat with a fake temperature, blocking any automation I could do.

**Comment by michaelthompson1991** [comment]
> Ditto, can’t figure out how to use this. I have a thermometer and a smart plug, really hoping I can use this to combine the two into a thermostat in HomeKit.
> 
> This plugin also seems to override the readout of the actual thermostat with a fake temperature, blocking any automation I could do.

Good luck! I still haven’t worked it out 🤔

**Comment by nickstx** [comment]
> > Ditto, can’t figure out how to use this. I have a thermometer and a smart plug, really hoping I can use this to combine the two into a thermostat in HomeKit.
> > This plugin also seems to override the readout of the actual thermostat with a fake temperature, blocking any automation I could do.
> 
> Good luck! I still haven’t worked it out 🤔

Figured it out! My setup is below

- This plug-in
- Meross Thermostat
- Meross Smart Plug with a heater plugged in
- https://github.com/kbrashears5/typescript-homebridge-schedule

I have the Homebridge schedule running every minute. Then a Home automation that is triggered by the switch belonging to the home schedule plugin.

- The automation checks if the thermostat is on or off 
- - If on, check desired temperature of the thermostat
- - - If desired temp is > current temp from Meross Thermostat, turn plug on
- - - else turn plug off
- - if off, turn smart plug off

I then have two more automations, one to turn the thermostat on at 08:00 and one turning it off at 17:00. Works great now!

![715A7580-2BDD-43F0-95DD-2D322C19F97E](https://user-images.githubusercontent.com/22432139/197953724-aae94af2-8a60-4813-90ed-7872a1f7b992.png)
![D27AC6CB-DAC6-4823-BD82-DFEC6A8DC3D8](https://user-images.githubusercontent.com/22432139/197953753-ace95bca-8ce8-4a62-b42e-c0bb6ee3bd8e.png)

**Comment by michaelthompson1991** [comment]
Could just be me here but could you not do that natively in HomeKit without this homebridge plugin? I’m struggling to see where you used it 🤷🏼‍♂️Sent from my iPhoneOn 26 Oct 2022, at 07:41, Nick Stocks ***@***.***> wrote:﻿


Ditto, can’t figure out how to use this. I have a thermometer and a smart plug, really hoping I can use this to combine the two into a thermostat in HomeKit.
This plugin also seems to override the readout of the actual thermostat with a fake temperature, blocking any automation I could do.

Good luck! I still haven’t worked it out 🤔

Figured it out! My setup is below

This plug-in
Meross Thermostat
Meross Smart Plug with a heater plugged in
https://github.com/kbrashears5/typescript-homebridge-schedule

I have the Homebridge scheduler running every minute. Then a Home automation that is triggered by the schedule.

The automation checks if the thermostat is on or off


If on, check desired temperature of the thermostat






If desired temp is > current temp from Meross Thermostat, turn plug on








else turn plug off






if off, turn smart plug off



I then have two more automations, one to turn the thermostat on at 08:00 and one turning it off at 17:00. Works great now!

**Comment by nickstx** [comment]
> Could just be me here but could you not do that natively in HomeKit without this homebridge plugin? I’m struggling to see where you used it 🤷🏼‍♂️Sent from my iPhoneOn 26 Oct 2022, at 07:41, Nick Stocks ***@***.***> wrote:﻿ Ditto, can’t figure out how to use this. I have a thermometer and a smart plug, really hoping I can use this to combine the two into a thermostat in HomeKit. This plugin also seems to override the readout of the actual thermostat with a fake temperature, blocking any automation I could do. Good luck! I still haven’t worked it out 🤔 Figured it out! My setup is below This plug-in Meross Thermostat Meross Smart Plug with a heater plugged in https://github.com/kbrashears5/typescript-homebridge-schedule I have the Homebridge scheduler running every minute. Then a Home automation that is triggered by the schedule. The automation checks if the thermostat is on or off If on, check desired temperature of the thermostat If desired temp is > current temp from Meross Thermostat, turn plug on else turn plug off if off, turn smart plug off I then have two more automations, one to turn the thermostat on at 08:00 and one turning it off at 17:00. Works great now! —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Because now I can have these widgets in my Home to control an electric radiator plugged into a smart plug. The only other way to do that would be to buy a proper smart electric heater, which cost a bomb and I don’t want.

![0CA21240-248F-4E3B-BA9E-1BA70D9F3073](https://user-images.githubusercontent.com/22432139/198021136-42c263c1-a5c3-4290-9585-9247ef18e61b.png)
![87E094D8-106F-4757-87DD-FD39A07F0A29](https://user-images.githubusercontent.com/22432139/198021142-4ef45873-3c68-4a32-9a6c-a3cdf6ec88d4.png)

**Comment by michaelthompson1991** [comment]
So where’s the temperature coming from?Sent from my iPhoneOn 26 Oct 2022, at 13:03, Nick Stocks ***@***.***> wrote:﻿

Could just be me here but could you not do that natively in HomeKit without this homebridge plugin? I’m struggling to see where you used it 🤷🏼‍♂️Sent from my iPhoneOn 26 Oct 2022, at 07:41, Nick Stocks @.> wrote:﻿ Ditto, can’t figure out how to use this. I have a thermometer and a smart plug, really hoping I can use this to combine the two into a thermostat in HomeKit. This plugin also seems to override the readout of the actual thermostat with a fake temperature, blocking any automation I could do. Good luck! I still haven’t worked it out 🤔 Figured it out! My setup is below This plug-in Meross Thermostat Meross Smart Plug with a heater plugged in https://github.com/kbrashears5/typescript-homebridge-schedule I have the Homebridge scheduler running every minute. Then a Home automation that is triggered by the schedule. The automation checks if the thermostat is on or off If on, check desired temperature of the thermostat If desired temp is > current temp from Meross Thermostat, turn plug on else turn plug off if off, turn smart plug off I then have two more automations, one to turn the thermostat on at 08:00 and one turning it off at 17:00. Works great now! —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

Because now I can have these widgets in my Home to control an electric radiator plugged into a smart plug. The only other way to do that would be to buy a proper smart electric heater, which cost a bomb and I don’t want.

**Comment by nickstx** [comment]
> So where’s the temperature coming from?Sent from my iPhoneOn 26 Oct 2022, at 13:03, Nick Stocks ***@***.***> wrote:﻿ Could just be me here but could you not do that natively in HomeKit without this homebridge plugin? I’m struggling to see where you used it 🤷🏼‍♂️Sent from my iPhoneOn 26 Oct 2022, at 07:41, Nick Stocks @.> wrote:﻿ Ditto, can’t figure out how to use this. I have a thermometer and a smart plug, really hoping I can use this to combine the two into a thermostat in HomeKit. This plugin also seems to override the readout of the actual thermostat with a fake temperature, blocking any automation I could do. Good luck! I still haven’t worked it out 🤔 Figured it out! My setup is below This plug-in Meross Thermostat Meross Smart Plug with a heater plugged in https://github.com/kbrashears5/typescript-homebridge-schedule I have the Homebridge scheduler running every minute. Then a Home automation that is triggered by the schedule. The automation checks if the thermostat is on or off If on, check desired temperature of the thermostat If desired temp is > current temp from Meross Thermostat, turn plug on else turn plug off if off, turn smart plug off I then have two more automations, one to turn the thermostat on at 08:00 and one turning it off at 17:00. Works great now! —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.> Because now I can have these widgets in my Home to control an electric radiator plugged into a smart plug. The only other way to do that would be to buy a proper smart electric heater, which cost a bomb and I don’t want. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

A Meross Thermostat, via Homebridge cos it’s not a HomeKit device

**Comment by michaelthompson1991** [comment]
Yeah makes sense now, I think 🤣Sent from my iPhoneOn 26 Oct 2022, at 16:08, Nick Stocks ***@***.***> wrote:﻿

So where’s the temperature coming from?Sent from my iPhoneOn 26 Oct 2022, at 13:03, Nick Stocks @.> wrote:﻿ Could just be me here but could you not do that natively in HomeKit without this homebridge plugin? I’m struggling to see where you used it 🤷🏼‍♂️Sent from my iPhoneOn 26 Oct 2022, at 07:41, Nick Stocks @.> wrote:﻿ Ditto, can’t figure out how to use this. I have a thermometer and a smart plug, really hoping I can use this to combine the two into a thermostat in HomeKit. This plugin also seems to override the readout of the actual thermostat with a fake temperature, blocking any automation I could do. Good luck! I still haven’t worked it out 🤔 Figured it out! My setup is below This plug-in Meross Thermostat Meross Smart Plug with a heater plugged in https://github.com/kbrashears5/typescript-homebridge-schedule I have the Homebridge scheduler running every minute. Then a Home automation that is triggered by the schedule. The automation checks if the thermostat is on or off If on, check desired temperature of the thermostat If desired temp is > current temp from Meross Thermostat, turn plug on else turn plug off if off, turn smart plug off I then have two more automations, one to turn the thermostat on at 08:00 and one turning it off at 17:00. Works great now! —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.> Because now I can have these widgets in my Home to control an electric radiator plugged into a smart plug. The only other way to do that would be to buy a proper smart electric heater, which cost a bomb and I don’t want. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

A Meross Thermostat, via Homebridge cos it’s not a HomeKit device
